# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 09:10
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='轮播图', upload_to='banner', verbose_name='轮播图')),
                ('index', models.ImageField(default=0, help_text='轮播顺序', upload_to='', verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(help_text='商品唯一货号', max_length=20, verbose_name='商品唯一货号')),
                ('name', models.CharField(help_text='商品名', max_length=50, verbose_name='商品名')),
                ('good_brief', models.TextField(max_length=500, verbose_name='商品简单描叙')),
                ('good_desc', DjangoUeditor.models.UEditorField(blank=True, help_text='商品详情', null=True, verbose_name='商品详情')),
                ('goods_front_image', models.ImageField(help_text='商品封面', max_length=50, upload_to='goods/images', verbose_name='商品封面')),
                ('goods_num', models.IntegerField(default=0, help_text='商品库存量', verbose_name='商品库存量')),
                ('market_price', models.IntegerField(default=0, help_text='市场价格', verbose_name='市场价格')),
                ('shop_price', models.FloatField(default=0, help_text='本店价格', verbose_name='本店价格')),
                ('ship_free', models.BooleanField(default=False, help_text='是否包邮', verbose_name='是否包邮')),
                ('is_new', models.BooleanField(default=False, help_text='是否新品', verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热卖', verbose_name='是否热卖')),
                ('sold_num', models.IntegerField(default=0, help_text='已出售数量', verbose_name='已出售数量')),
                ('fav_num', models.IntegerField(default=0, help_text='收藏数量', verbose_name='收藏数量')),
                ('click_num', models.IntegerField(default=0, help_text='点击量', verbose_name='点击量')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类别名', max_length=50, verbose_name='类别名')),
                ('code', models.CharField(help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.CharField(help_text='类别描述', max_length=200, verbose_name='类别描述')),
                ('category_type', models.IntegerField(blank=True, choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', null=True, verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类目级别', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=30, verbose_name='品牌名')),
                ('desc', models.TextField(default='', help_text='品牌描叙', max_length=200, verbose_name='品牌描叙')),
                ('image', models.ImageField(help_text='品牌logo', max_length=200, upload_to='brands/', verbose_name='品牌logo')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, help_text='商品类目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='图片', upload_to='goods/', verbose_name='图片')),
                ('image_url', models.URLField(blank=True, help_text='图片地址', max_length=300, null=True, verbose_name='图片地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('goods', models.ForeignKey(help_text='商品名', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='goods.Goods', verbose_name='商品名')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', help_text='热搜词', max_length=20, verbose_name='热搜词')),
                ('index', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '热搜词',
                'verbose_name_plural': '热搜词',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.GoodsCategory', verbose_name='商品类目')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='商品', to='goods.Goods')),
            ],
            options={
                'verbose_name': '首页商品类别广告',
                'verbose_name_plural': '首页商品类别广告',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(help_text='商品名', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品名'),
        ),
    ]
