# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180224_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(help_text='商品封面', max_length=50, upload_to='goods/images/', verbose_name='商品封面'),
        ),
    ]
