# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('success', '成功'), ('cancel', '取消'), ('wait', '待支付')], help_text='支付状态', max_length=10, null=True, verbose_name='支付状态'),
        ),
    ]
