# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0006_auto_20180227_1600'),
        ('user_operation', '0002_auto_20180224_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
